const skills = [
    "JavaScript",
    "TypeScript",
    "SQL",
    "React",
    "Next",
    "Vue",
    "Nuxt",
    "Node",
    "Express",
    "Nest",
    "Testes unitários",
    "Jest",
    "Vitest",
    "MySQL",
    "SQL Server",
    "MongoDB",
    "Mongoose",
    "Sequelize",
    "TypeORM",
    "CSS",
    "SASS",
    "styled components",
    "Bootstrap",
    "Reactstrap",
    "Bootstrap Vue",
    "Vuetify",
    "Material UI",
    "Git",
    "Google Maps API",
    "OpenStreetMap API",
    "Google Recaptcha",
    "CoinMarketCap API",
    "JWT",
    "Linux",
    "Clean Architecture",
    "SOLID",
    "Heroku",
    "Vercel",
    "Hostinger",
    "AWS RDS",
    "AWS EC2",
    "AWS Load Balancer",
    "AWS Route 53",
    "Google Domains",
    "VPS",
    "Apache",
    "Docker",
    "Docker Compose",
    "SSH",
    "GitHub Actions"
];

export async function getSkills() {
    try {
        return { status: true, content: skills }
    } catch (error) {
        return { status: false, error }
    }
}