const skills = [
    "JavaScript",
    "TypeScript",
    "React",
    "React Native",
    "Next",
    "Vue",
    "Nuxt",
    "Node",
    "ExpressJs",
    "krakenjs",
    "MySQL",
    "SQL Server",
    "MongoDB",
    "HTTP Requests",
    "Promises",
    "Mongoose",
    "Sequelize",
    "phpMyAdmin",
    "Azure Data Studio",
    "DBeaver",
    "CSS",
    "SASS",
    "Bootstrap",
    "Reactstrap",
    "Bootstrap Vue",
    "Vuetify",
    "Animations",
    "Transitions",
    "Flexbox",
    "Grid",
    "Responsividade",
    "Git",
    "GitHub",
    "GitLab",
    "BitBucket",
    "Azure Repos",
    "Google Maps API",
    "OpenStreetMap API",
    "Google Recaptcha",
    "Google Domains",
    "CoinMarketCap API",
    "JWT",
    "Linux",
    "LAMP",
    "WAMP",
    "npm",
    "yarn",
    "MVC",
    "Trello",
    "Slack",
    "Teams",
    "Azure DevOps",
    "Heroku",
    "Vercel",
    "Hostinger",
    "AWS RDS",
    "AWS EC2",
    "AWS Load Balancer",
    "AWS Route 53",
    "DNS",
    "Apache"
];

export async function getSkills() {
    try {
        return { status: true, content: skills }
    } catch (error) {
        return { status: false, error }
    }
}